### ISSUE TITLE
Add parameter if save or not

### ISSUE THREAD

**Issue by KenkenGoda** [tenajima/nullpom#17]
- I think the auto save flow is not always necessary. It should be selectable for user.

**Comment by tenajima** [comment]
I think saving result is important because null importance is taking a lot of time.
If I fix #16 and #15, this issue won't problem?

**Comment by KenkenGoda** [comment]
When I run on google colaboratory, the directory is made on the top directory as `YYYYmmdd_HMS` by default. It does't matter if the directory will be made on a simple directory like `./output`.
