### ISSUE TITLE
Separate parameter for LightGBM parameters

### ISSUE THREAD

**Issue by KenkenGoda** [tenajima/nullpom#18]
- It should separate to set parameters for LightGBM to model parameters and fit parameters. (e.g. num_boosting_rounds, early_stopping_rounds) Otherwise, `UserWarning` of lightgbm.engine occurs.

**Comment by tenajima** [comment]
Now, I don't implement that parameter because of being quiet `UserWarning`.
I will implement it when it becomes a functional necessity.
